export const SECTIONS = {
  WELCOME: 'WELCOME',
  TODO: 'TODO',
  STICKY: 'STICKY',
  SETTINGS: 'SETTINGS',
};

export const ACTIONS = {
  CHANGE_SECTION: 'CHANGE_SECTION',
  CHANGE_NAME: 'CHANGE_NAME',
  ADD_TODO: 'ADD_TODO',
  CLEAN: 'CLEAN',
  DELETE_TODO: 'DELETE_TODO',
  MOVE_TO_IN_PROGRESS: 'MOVE_TO_IN_PROGRESS',
  MOVE_TO_TO_DO: 'MOVE_TO_TO_DO',
  MOVE_TO_DONE: 'MOVE_TO_DONE',
  ADD_STICKY: 'ADD_STICKY',
  DELETE_STICKY: 'DELETE_STICKY'
};

export const STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  TO_DO: 'TO_DO',
  DONE: 'DONE',
};
